### ISSUE TITLE
Heroku Free Dynos: "fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached"

### ISSUE THREAD

**Issue by ogsamrat** [fake-useragent/fake-useragent#158]
### fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached Possible Fix

- Kindly note that the free dynos services of **Heroku**, a hosting provider, has stopped which is causing **fake-useragent** to crash for all users. 
- fake-useragent hosted one or more of its services to gather info on heroku at https://fake-useragent.herokuapp.com/browsers/0.1.11 which is eventually down after the services got stopped.

**To Developers (fake-useragent, @fake-useragent, @hellysmile):** Upgrade to paid dynos asap for us to use your services, or move to a vps
**To Developers (rest, like me):** There's nothing we can do on our sides, either wait or use some other pypi package

**Comment by ogsamrat** [comment]
Some quite big projects of mine and thousands of others, are very much dependent on your package, so kindly get your services restored as early as possible, thank you :) @hellysmile @danger89

**Comment by melroy89** [comment]
You are using a very old version. Try to use the latest version: `pip install --upgrade fake-useragent`

**EDIT:** Also note that the package name is renamed from `fake_useragent` to `fake-useragent`.

**Comment by reactiver001** [comment]
I have the same problem and use last version :/

**Comment by acibiber53** [comment]
I had this same issue in the morning but it has been resolved after upgrading to the latest version from 0.1.11.

Edit: Then I had another issue when I tried to turn my .py files into exe file using pyinstaller, which I did the same way for 2 years. `importlib.metadata.PackageNotFoundError: fake-useragent` is the error I get. Looking into it. One [SO post about another package](https://stackoverflow.com/questions/73797873/importlib-metadata-packagenotfounderror-no-package-metadata-was-found-for-pypro) says after version upgrade, new version requires dist-info to be present, which doesn't work  when you have one file installation.

But I guess now it is a different issue.

Edit 2: It is solved by adding dist-info of fake-useragent 1.1.0 into setup file with "--add-data" command. All good now

Edit 3: After some time I started to get ModuleNotFoundError for "fake_useragent.data" from pyinstaller exe file, which originates from FileNotFoundError for the relevant directory. Interestingly, when the pyinstaller creates exe file, it doesn't add the fake_useragent library files into the package. "--add-data" solves that problem as well. Let's see how long will this solution hold up.

**Comment by ogsamrat** [comment]
Looks like i have been using the `fake_useragent` package instead of `fake-useragent`, even though the both pypi redirects to [fake-useragent](https://pypi.org/project/fake-useragent/), as in [fake_useragent](https://pypi.org/project/fake_useragent/)!
Anyways if anyone like me has been doing the same, make the changes and it's gonna be fixed.

**Comment by EmiliaDevs** [comment]
> 

Thanks for the suggestions, I'll definitely consider the changes during an exe conversion.

**Comment by ogsamrat** [comment]
> > 
> 
> Thanks for the suggestions, I'll definitely consider the changes during an exe conversion.



> I had this same issue in the morning but it has been resolved after upgrading to the latest version from 0.1.11.
> 
> Edit: Then I had another issue when I tried to turn my .py files into exe file using pyinstaller, which I did the same way for 2 years. `importlib.metadata.PackageNotFoundError: fake-useragent` is the error I get. Looking into it. One [SO post about another package](https://stackoverflow.com/questions/73797873/importlib-metadata-packagenotfounderror-no-package-metadata-was-found-for-pypro) says after version upgrade, new version requires dist-info to be present, which doesn't work when you have one file installation.
> 
> But I guess now it is a different issue.
> 
> Edit 2: It is solved by adding dist-info of fake-useragent 1.1.0 into setup file with "--add-data" command. All good now.

Thanks for the suggestions, I'll definitely consider the changes during an exe conversion.

**Comment by melroy89** [comment]
> Edit 2: It is solved by adding dist-info of fake-useragent 1.1.0 into setup file with "--add-data" command. All good now.

Interesting since there is indeed an other issue on this github repo exactly about pyinstaller. So what can I do so solve this problem for all windows users in my code base?

**Comment by cmaronchick** [comment]
Hi @acibiber53, thanks for the guidance. I'm having a new problem I'm hoping you can help me with.
After upgrading to fake-useragent 1.1, my python file runs locally, but when I upload to Lambda, I get this error: 
[ERROR] AttributeError: 'PosixPath' object has no attribute 'read_text'

Any idea what might be causing that and if I need to upgrade a different package? Thanks in advance!

Edit: I found an [Github discussion](https://gitlab.com/python-devs/importlib_metadata/-/issues/79) that cited having pathlib installed specifically in the requirements. Uninstalling it and uploading the new package solved the problem.

**Comment by xiankgx** [comment]
Please fix this ASAP. This error is breaking alot of stuffs.

**Comment by JulianBlin** [comment]
> Please fix this ASAP. This error is breaking alot of stuffs.

You can easily switch to [anti-useragent](https://github.com/ihandmine/anti-useragent) by changing your requirements.txt and your import line. Class names are similar.
That's what I did. 
Obviously this project here is not maintained anymore :(

**Comment by melroy89** [comment]
Ow it's maintained. But nobody helps me with the fix for windows (pyinstaller). I don't run Windows.

**Comment by melroy89** [comment]
> Looks like i have been using the `fake_useragent` package instead of `fake-useragent`, even though the both pypi redirects to [fake-useragent](https://pypi.org/project/fake-useragent/), as in [fake_useragent](https://pypi.org/project/fake_useragent/)! 

It looks like indeed it's renamed when we migrated to `pyproject.toml` Python setup.

**Comment by mathix420** [comment]
For me the issue was using `cloudflare-warp` while trying to `pip install fake-useragent` inside a Docker build with `python:3.9-alpine` as image.
Solved my issue by disabling warp for the action.
```
warp-cli disable-always-on
```
It seems docker is super slow to downloading deps with warp.
Very strange, but worked, hope it can help someone else.

**Comment by melroy89** [comment]
If you are still using an old version, execute: `pip install --upgrade fake-useragent`

Again, it should use a local `browsers.json` file as data source. It will never connect to the internet anymore.
